<?php

declare(strict_types=1);

namespace App\Filament\Pages\Auth;

use App\Enums\TenantType;
use App\Helpers\FormatterHelper;
use App\Models\Tenant;
use Carbon\Carbon;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\TextEntry;
use Filament\Pages\Tenancy\RegisterTenant;
use Filament\Schemas\Schema;
use Leandrocfe\FilamentPtbrFormFields\Document;

final class RegisterTeam extends RegisterTenant
{
    protected bool $hasTopbar = false;

    public static function getLabel(): string
    {
        return 'Criar empresa';
    }

    public function hasLogo(): bool
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('trial_info')
                    ->label('7 DIAS GRÁTIS')
                    ->state('Teste completo sem limitações.')
                    ->badge()
                    ->color('success')
                    ->size('lg')
                    ->extraAttributes(['class' => 'text-center'])
                    ->columnSpanFull(),

                TextEntry::make('pricing_info')
                    ->hiddenLabel()
                    ->state('Após o período de teste: R$ 29,90/mês (sem contratos ou taxas ocultas)')
                    ->extraAttributes(['class' => 'text-center text-sm text-gray-600 dark:text-gray-400 font-medium'])
                    ->columnSpanFull(),

                TextEntry::make('guarantee')
                    ->hiddenLabel()
                    ->state('🔒 Seus dados estão seguros | ⚡ Cancele quando quiser, sem multas')
                    ->extraAttributes(['class' => 'text-center text-xs text-gray-500 dark:text-gray-500 mt-2'])
                    ->columnSpanFull(),

                TextEntry::make('billing_date_info')
                    ->hiddenLabel()
                    ->state(function () {
                        $billingDate = Carbon::now()->addDays(7);

                        return '💳 Primeira cobrança somente em: '.$billingDate->format('d/m/Y').' (daqui a 7 dias)';
                    })
                    ->extraAttributes(['class' => 'text-center text-sm bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 p-3 rounded-lg border border-blue-200 dark:border-blue-800 font-medium mt-4'])
                    ->columnSpanFull(),
                TextInput::make('name')
                    ->label('Nome da empresa')
                    ->required()
                    ->maxLength(255),
                Document::make('document')
                    ->label('CPF/CNPJ')
                    ->dynamic(),
                TextInput::make('website')
                    ->label('Website')
                    ->url()
                    ->maxLength(255),
                Select::make('type')
                    ->label('Tipo de Empresa')
                    ->options(TenantType::toSelectArray())
                    ->default(TenantType::OTHER->value)
                    ->required()
                    ->searchable()
                    ->helperText('Selecione o tipo de negócio da sua empresa'),

            ]);
    }

    protected function handleRegistration(array $data): Tenant
    {
        $data['slug'] = Tenant::generateUniqueSlug($data['name']);
        $data['document'] = FormatterHelper::onlyNumbers($data['document'] ?? '');
        $team = Tenant::query()->create($data);

        $team->members()->attach(auth()->user());

        return $team;
    }
}
