<?php

declare(strict_types=1);

namespace App\Filament\Pages\Auth;

use App\Enums\TenantType;
use App\Helpers\FormatterHelper;
use App\Models\Tenant;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\ViewField;
use Filament\Infolists\Components\TextEntry;
use Filament\Pages\Tenancy\RegisterTenant;
use Filament\Schemas\Schema;
use Leandrocfe\FilamentPtbrFormFields\Document;

final class RegisterTeam extends RegisterTenant
{
    public static function getLabel(): string
    {
        return 'Criar empresa';
    }

    public function hasLogo(): bool
    {
        return true; // TODO: Change the autogenerated stub
    }

    protected bool $hasTopbar = false;

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('info')
                    ->label('Preencha os dados abaixo para criar sua conta.')
                    ->state('Teste gratuitamente por 7 dias.')
                    ->badge()
                    ->extraAttributes(['class' => 'bg-primary-100 text-primary-800 dark:bg-primary-900 dark:text-primary-200'])
                    ->columnSpanFull(),
                TextInput::make('name')
                    ->label('Nome da empresa')
                    ->required()
                    ->maxLength(255),
                Document::make('document')
                    ->label('CPF/CNPJ')
                    ->dynamic(),
                TextInput::make('website')
                    ->label('Website')
                    ->url()
                    ->maxLength(255),
                Select::make('type')
                    ->label('Tipo de Empresa')
                    ->options(TenantType::toSelectArray())
                    ->default(TenantType::OTHER->value)
                    ->required()
                    ->searchable()
                    ->helperText('Selecione o tipo de negócio da sua empresa'),

            ]);
    }

    protected function handleRegistration(array $data): Tenant
    {
        $data['slug'] = Tenant::generateUniqueSlug($data['name']);
        $data['document'] = FormatterHelper::onlyNumbers($data['document'] ?? '');
        $team = Tenant::query()->create($data);

        $team->members()->attach(auth()->user());

        return $team;
    }
}
